### ISSUE TITLE
DeadLock occur

### ISSUE THREAD

**Issue by mintzhao** [Rogerzhao/dirscan_tool#1]
## bug describe

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.(*DirScanner).ScanFileInfo(0xc82005c080)
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/dirscan_tool/dirscan.go:78 +0xdf
main.main()
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/dirscan_tool/main.go:59 +0x3cd

goroutine 134 [chan send]:
main.(*FileInfo).genSha1(0xc82011cf90, 0x0, 0x0)
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/dirscan_tool/dirscan.go:45 +0x5b1
created by main.(*DirScanner).ScanFileInfo
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/dirscan_tool/dirscan.go:76 +0xad

goroutine 17 [chan receive]:
github.com/Rogerzhao/xmlib/xmlog.(*Xmlogger).WatchErrors(0xc820016330, 0xc820012588, 0x8, 0xc82001243b, 0x3)
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/xmlib/xmlog/xmlog.go:132 +0x452
created by github.com/Rogerzhao/xmlib/xmlog.WatchErrors
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/xmlib/xmlog/xmlog.go:240 +0x5f

goroutine 7 [chan receive]:
main.(*DirScanner).fileStore(0xc82005c080, 0x0, 0x0)
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/dirscan_tool/dirscan.go:162 +0x148
created by main.main
    /Users/mint/develop/gopath/src/github.com/Rogerzhao/dirscan_tool/main.go:57 +0x3bf

```
## solution

I have read your code, better than me.
And the bug maybe due to dirscan.go ScanFileInfo method. More specify, due to syncChan

```

func (d *DirScanner) ScanFileInfo() {
    d.scanDirWithFilter()
    var count int64
    count = 0
    for _, fileInfo := range d.fileInfos {
        go fileInfo.genSha1()
        count++
        <-concurrentChan
    }

    // sync
    for i := int64(0); i < count; i++ {
        <-syncChan // this line
    }
    close(outputChan)
    xmlog.Infof("end scan file info ,get %d files", count)
}


func (f *FileInfo) genSha1() (err error) {
    buf, err := ioutil.ReadFile(f.fileName)
    if err != nil {
        xmlog.ERROR(err)
        return
    }

    h := sha1.New()
    io.WriteString(h, string(buf))
    f.sha1 = fmt.Sprintf("%x", h.Sum(nil))
    output := fmt.Sprintf("%s,%s,%d", f.fileName, f.sha1, f.size)
    outputChan <- output
    syncChan <- 1 // this line

    concurrentChan <- 1
    return
}
```

**Comment by Rogerzhao** [comment]
I have the dead lock fixed. Please kindly check again. Thanks very much. Use channel to sync should be enhanced in the future.
